server:
  port: 6506
  servlet:
    context-path: /mailing

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST}:${EUREKA_SERVER_PORT}/eureka
  instance:
    hostname: ${EUREKA_SERVER_HOST}
    prefer-ip-address: true


spring:
  application:
    name: MAILING-SERVICE


  datasource:
    url: jdbc:mariadb://${DATABASE_HOST}/${DATABASE_NAME}
    username: ${DATABASE_USERNAME}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver


  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
logging:
  level:
    root: INFO
  file:
    name: log/dev.log
