server:
  port: 6508
  servlet:
    context-path: /seal

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://123.24.142.93:6503/eureka
  instance:
    hostname: localhost
    prefer-ip-address: true


spring:
  application:
    name: SEAL-SERVICE

  datasource:
    url: jdbc:mariadb://123.24.142.93:82/mailing-service
    username: mber
    password: techbro@123
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: false
  jackson:
    serialization:
      WRITE_DATES_AS_TIMESTAMPS: false
    time-zone: UTC

jwt:
  secret: BvPHGM8C0ia4uOuxxqPD5DTbWC9F9TWvPStp3pb7ARo0oK2mJ3pd3YG4lxA9i8bj6OTbadwezxgeEByY

logging:
  level:
    root: INFO
    com:
      querydsl:
        sql: DEBUG
  file:
    name: log/dev.log